image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - npm
  - nodejs
secrets:
  - ee56e449-e495-4364-b489-5d93d5c273da
environment:
  site: ihavea.quest
  # https://docs.npmjs.com/cli/v6/using-npm/config#progress
  CI: true
  NETLIFY_SITE_ID: 2535557f-f509-4bc8-a070-b0d90c171f0d
tasks:
  - install: |
      cd $site
      npm install
  - package: |
      cd $site
      NODE_ENV=production npm run build
      tar -C _site -cvz . > ../site.tar.gz
  - deploy: |
      cd $site
      {
        set +x
        . ~/.buildsecrets
        set -x
      }
      export NETLIFY_AUTH_TOKEN
      npm run deploy
