baseurl = "https://ihavea.quest"
languageCode = "en-us"
theme = "terminal"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "blog"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Last Updated"

  # whether to show a page's estimated reading time
  readingTime = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = true

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

[params.contact]
  email = 'txtsd@ihavea.quest'

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "I have a quest!"

    [languages.en.params]
      subtitle = "All about txtsd and their antics"
      owner = "txtsd"
      keywords = "txtsd, minecraft, Arch Linux, Free and Open Source Software, FOSS, FLOSS, copyleft licenses, GPL, AGPL, autoplaying bots"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "QUEST"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "projects"
          name = "Projects"
          url = "/projects"
          weight = 10
        [[languages.en.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/blog"
          weight = 20
        [[languages.en.menu.main]]
          identifier = "misc"
          name = "Misc"
          url = "/misc"
          weight = 30
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
          weight = 40

[module]
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
# [[module.imports]]
#   path = 'github.com/panr/hugo-theme-terminal/v4'
