name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hugo-version: ['0.136.5', 'latest']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Install dependencies & build
        run: |
          hugo

